name: Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: 46.101.149.100
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: whoami
