name: remote ssh command
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          source ~/.nvm/nvm.sh
          pm2 startOrRestart ${{ secrets.PROD_JEDI_BOT_APP_PATH }}/ecosystem.config.js --env development
