name: Production deploy
on:
  push:
    branches:
      - master
jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ${{ secrets.PROD_JEDI_BOT_APP_PATH }}
          git pull origin dev
          source ~/.nvm/nvm.sh
          npm i
          pm2 startOrRestart ecosystem.config.js --env production
